BOT_TOKEN = "ВАШ_ТОКЕН_БОТА"
ADMIN_ID = 123456789  # Ваш Telegram ID
BOT_NAME = "GiftsMMS"

TON_API_KEY = "ВАШ_API_КЛЮЧ_ОТ_TONCENTER"
BOT_WALLET_MNEMONIC = "ваша мнемоническая фраза из 12 слов"
BOT_WALLET_ADDRESS = "EQD..."

TON_TO_STARS_RATE = 1000
MAX_DEPOSIT_STARS = 25
MAX_BET_STARS = 15
MAX_BET_TON = 0.15
MAX_PLAYERS_IN_BATTLE = 10

DB_NAME = "giftsmm.db"
